#!/bin/bash

####################################
##	License
####################################
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

####################################
##	Main Part
####################################

##  Source libraries and config
lib=/usr/lib/mkpdf/lib
bin=/usr/lib/mkpdf/bin
data=/usr/share/mkpdf
conf=$HOME/.config/mkpdf
source $lib/help.sh || exit 1
source $lib/general.sh || exit 1
source $lib/run.sh || exit 1
source $data/config || exit 1
[[ -f $conf/config ]] && source $conf/config


##  Get Variables
read_input $@
get_template


##  Set up tmpdir
x="$(echo $template | rev | cut -d '/' -f 1 | rev)"
tmpdir="/tmp/mkpdf/$title/$x"
! [[ -d $tmpdir ]] && mkdir -p $tmpdir
rm -f $tmpdir/latexmk.log


##  Write helper files
if [[ $mode = toc ]]; then
    read_toc meta $tocdir/toc.conf > $tmpdir/head.md
    files="$tmpdir/head.md $files"
fi
if [[ $ftype = bib ]]; then
    parse_bib_titleblock $files > $tmpdir/head.md
fi


##  Set options
pandoc_options+=" -o $tmpdir/master.tex"
if [[ $ftype = bib ]]; then
    
    pandoc_options+=" -t latex $tmpdir/head.md"
    for f in $files; do
        if ! [[ $(file $f | grep PDF) ]]; then
            pandoc_options+=" --bibliography=$f"
        fi
    done
    if [[ -f $conf/bib.md ]]; then
        pandoc_options+=" $conf/bib.md"
    else
        pandoc_options+=" /usr/share/mkpdf/bib.md"
    fi
else
    pandoc_options+=" $files"
    if [[ $ttype = latex ]]; then
        pandoc_options+=" -t latex"
    elif [[ $ttype = beamer ]]; then
        pandoc_options+=" -t beamer"
    fi
fi


# Be smart about filters
[[ $ttype = beamer ]] && handout_filter=0
[[ $ftype = bib ]] && handout_filter=0
[[ $handout_filter  = 1 ]] && pandoc_options+=" --filter=$bin/pandoc-handout "


##  Run stuff
run_pandoc
[[ $furbishtex_postprocessor ]] && $bin/furbishtex $tmpdir/master.tex
run_latexmk


##  Copy output to destination (and maybe preview)
echo "    Exporting output: $output"
cp -f $tmpdir/latexmk/master.pdf $output
[[ $auto_preview = 1 ]] && exo-open $output &

exit 0
