#!/bin/sh

set -f; IFS='|'     # Use pipe for variable expansion (zenity default)

get_filename() {
    get_mode() {
        # Ask which mode to run in
        # Returns:  0 - single file
        #           1 - multiple files
        #           2 - directory (toc-mode)
        zenity --title="mkpdf" --list \
            --hide-header --hide-column=1 --print-column=1 \
            --column="Nr" --column="Description" \
            --text="Woraus soll ein pdf erstellt werden?" \
            0 "Einzelne Datei auswählen" \
            1 "Mehrere Dateien auswählen" \
            2 "Ordner auswählen (toc-mode)"
    }
    mode=$(get_mode)
    test "$mode" || exit 0    # Exit on cancel or empty selection

    # Show file-chooser dialog and output filenames
    if test $mode = 0; then     # single file mode
        zenity --title="mkpdf" --file-selection
    elif test $mode = 1; then   # multiple file mode
        zenity --title="mkpdf" --file-selection --multiple
    elif test $mode = 2; then   # directory mode
        zenity --title="mkpdf" --file-selection --directory
    fi
}

if test $# -eq 0; then
    filenames="$(get_filename)"
    test "$filenames" || exit 0    # Exit on cancel
else
    filenames="$@"
fi

#for file in $filenames; do
#    if test -f "$file"; then
#        echo $file is a file
#    elif test -d "$file"; then
#        echo $file is a directory
#    else
#        echo $file is invalid
#    fi
#done

mkpdf -p $filenames |
        zenity --title="mkpdf" --progress \
            --pulsate --auto-kill --auto-close \
            --text="pdf wird erstellt ..."
